[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"
description = "{{project-name}}, a rusty-hermit application"
repository = "https://github.com/rust-learn-days/{{project-name}}"
[dependencies]
